services:
  server-sent-events:
    extends:
      file: docker-compose.yaml
      service: server-sent-events
    build:
      target: development
    image: server-sent-events-test
    container_name: server-sent-events-test
    command: npm run test
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
