services:
  server-sent-events:
    build:
      target: development
    image: server-sent-events-development
    container_name: server-sent-events-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - server-sent-events

networks:
  server-sent-events:
    driver: bridge
    name: server-sent-events
